// Generated by CoffeeScript 1.10.0
import {Service} from '../src/at-angular';
import {testModule} from './module';
import {TestServiceTwo} from './service';
import 'angular-mocks';

describe('@Service', () => {

  let deps = null;
  let testServiceTwo: TestServiceTwo = null;

  beforeEach(angular.mock.module(testModule.name));

  beforeEach(inject((_$http_, _$parse_, _TestServiceTwo_) => {
    deps = {
      $http: _$http_,
      $parse: _$parse_
    };
    testServiceTwo = _TestServiceTwo_;
  }));

  it('should be defined', () => {
    expect(Service).toEqual(jasmine.any(Function));
  });

  it('should instantiate decorated class as new service', () => {
    expect(testServiceTwo).toBeDefined();
    expect(testServiceTwo).toEqual(jasmine.any(TestServiceTwo));
  });

  it('should pass proper dependencies (based on static member "$inject") to service constructor', () => {
    let i, len, ref, results;
    ref = TestServiceTwo.$inject;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      let dep = ref[i];
      results.push(expect(testServiceTwo['$' + (dep.replace('$', ''))]).toBe(deps[dep]));
    }
    return results;
  });
});
